# Generated by Django 2.2.5 on 2021-02-18 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandemicsprediction', '0002_auto_20210218_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingoptions',
            name='trainedFeatures',
        ),
        migrations.AddField(
            model_name='trainingoptions',
            name='settings',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='TrainedFeature',
        ),
    ]
